version: '3.4'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - gps-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 9EjVForD
      MYSQL_DATABASE: gps
      MYSQL_PASSWORD: 9EjVForD
      MYSQL_USER: gps
    ports:
      - 3306:3306
    networks:
      - default
      - gps
  nodered:
    image: nodered/node-red-docker:v8
    networks:
      - default
      - gps
    volumes:
      - ./node-red-data:/data
    ports:
      - 1880:1880
  redis:
    image: redis:4.0
    volumes:
      - ./redisdata:/data
volumes:
  gps-mysql:
    external : true
networks:
  gps:
    driver: overlay

